/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LocalRent;
import javax.swing.*;
import javax.swing.border.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;

/**
 *
 * @author Sumit
 */
public class HRegister extends JFrame {
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;

    /**
     * Creates new form HRegister
     */
    public HRegister() {
        super("House Register");
        initComponents();
        conn = RentDatabase.connectDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        houseRegisterPanel = new JPanel();
        whitePanel = new JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        addHouseButton = new JButton();
        hRegisterClose = new JButton();
        houseId = new JTextField();
        numberOfRooms = new JTextField();
        address = new JTextArea();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        houseRegisterPanel.setBackground(new Color(0, 204, 204));
        houseRegisterPanel.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
        whitePanel.setBackground(new Color(255, 255, 255));

        jLabel1.setFont(new Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new Color(0, 204, 204));
        jLabel1.setText("House Details");

        jLabel2.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("House Id");

        jLabel3.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Total Rooms");

        jLabel4.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Address");

        addHouseButton.setBackground(new Color(0, 255, 204));
        addHouseButton.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        addHouseButton.setForeground(new Color(255, 255, 255));
        addHouseButton.setIcon(new ImageIcon("image\\plus.png")); // NOI18N
        addHouseButton.setText("Add House");
        addHouseButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        addHouseButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                addHouseButtonActionPerformed(evt);
            }
        });

        GroupLayout whitePanelLayout = new GroupLayout(whitePanel);
        whitePanel.setLayout(whitePanelLayout);
        whitePanelLayout.setHorizontalGroup(
            whitePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(whitePanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, whitePanelLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(whitePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, GroupLayout.Alignment.TRAILING)
                    .addComponent(addHouseButton, GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        whitePanelLayout.setVerticalGroup(
            whitePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(whitePanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(45, 45, 45)
                .addComponent(jLabel4)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addHouseButton)
                .addGap(27, 27, 27))
        );

        hRegisterClose.setBackground(new Color(255, 0, 0));
        hRegisterClose.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        hRegisterClose.setForeground(new Color(255, 255, 255));
        hRegisterClose.setText("X");
        hRegisterClose.setToolTipText("close");
        hRegisterClose.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                hRegisterCloseActionPerformed(evt);
            }
        });

        address.setColumns(20);
        address.setRows(5);

        GroupLayout houseRegisterPanelLayout = new GroupLayout(houseRegisterPanel);
        houseRegisterPanel.setLayout(houseRegisterPanelLayout);
        houseRegisterPanelLayout.setHorizontalGroup(
            houseRegisterPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(houseRegisterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(whitePanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(houseRegisterPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(houseRegisterPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(hRegisterClose))
                    .addGroup(houseRegisterPanelLayout.createSequentialGroup()
                        .addGroup(houseRegisterPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(houseRegisterPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                .addComponent(numberOfRooms, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addComponent(houseId, GroupLayout.Alignment.LEADING))
                            .addComponent(address, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 30, Short.MAX_VALUE))))
        );
        houseRegisterPanelLayout.setVerticalGroup(
            houseRegisterPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(houseRegisterPanelLayout.createSequentialGroup()
                .addGroup(houseRegisterPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(houseRegisterPanelLayout.createSequentialGroup()
                        .addComponent(hRegisterClose, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(houseId, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numberOfRooms, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(address, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addGroup(houseRegisterPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(whitePanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(houseRegisterPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(houseRegisterPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hRegisterCloseActionPerformed(ActionEvent evt) {//GEN-FIRST:event_hRegisterCloseActionPerformed
     this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_hRegisterCloseActionPerformed

    private void addHouseButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_addHouseButtonActionPerformed
            try{
             stmt = conn.createStatement();
             String add = address.getText();
             int room = Integer.parseInt(numberOfRooms.getText());
             String houseid = houseId.getText();
             String sql = "insert into house(houseId,totalRooms,address,vacantRoom)values('"+houseid+"','"+room+"','"+add+"','"+room+"')";
              stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "House Registered Successfully");
           this.dispose();
            }catch(HeadlessException | SQLException e) {
             JOptionPane.showMessageDialog(null, e);
          }
           

       
    }//GEN-LAST:event_addHouseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(() -> {
            new HRegister().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton addHouseButton;
    private JTextArea address;
    private JButton hRegisterClose;
    private JTextField houseId;
    private JPanel houseRegisterPanel;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JTextField numberOfRooms;
    private JPanel whitePanel;
    // End of variables declaration//GEN-END:variables
}
