/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LocalRent;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
/**
 *
 * @author sk995
 */
public class LoginForm extends JFrame {
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null,rs1 = null;
    public static boolean check = false;


    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        super("LoginForm");
        initComponents();
        conn = RentDatabase.connectDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new JPanel();
        jLabel6 = new JLabel();
        jLabel1 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        loginClose = new JButton();
        jPanel3 = new JPanel();
        userName = new JTextField();
        password = new JPasswordField();
        jLabel2 = new JLabel();
        loginButton = new JButton();
        registerButton = new JButton();
        jLabel5 = new JLabel();
        seePassword = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new Color(153, 0, 153));

        jLabel6.setIcon(new ImageIcon("image\\home-transparent-white-3.png")); // NOI18N

        jLabel1.setFont(new Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new Color(255, 153, 153));
        jLabel1.setText("Local Rent");

        jLabel3.setFont(new Font("Malgun Gothic Semilight", 1, 15)); // NOI18N
        jLabel3.setText("Username");

        jLabel4.setFont(new Font("Malgun Gothic Semilight", 1, 15)); // NOI18N
        jLabel4.setText("Password");

        loginClose.setBackground(new Color(255, 0, 51));
        loginClose.setFont(new Font("Cambria Math", 1, 18)); // NOI18N
        loginClose.setForeground(new Color(255, 255, 255));
        loginClose.setText("X");
        loginClose.setBorderPainted(false);
        loginClose.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                loginCloseActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new Color(255, 255, 255));

        userName.setFont(new Font("Tahoma", 1, 12)); // NOI18N
        userName.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });

        password.setFont(new Font("Tahoma", 1, 12)); // NOI18N

        jLabel2.setFont(new Font("Comic Sans MS", 1, 30)); // NOI18N
        jLabel2.setForeground(new Color(153, 0, 153));
        jLabel2.setText("LOGIN");

        loginButton.setBackground(new Color(255, 102, 204));
        loginButton.setFont(new Font("Comic Sans MS", 1, 12)); // NOI18N
        loginButton.setText("LOGIN");
        loginButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        loginButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        registerButton.setBackground(new Color(0, 255, 51));
        registerButton.setFont(new Font("Comic Sans MS", 1, 12)); // NOI18N
        registerButton.setText("REGISTER");
        registerButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        registerButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("(For new user)");

        seePassword.setIcon(new ImageIcon("image\\visibility-button.png")); // NOI18N
        seePassword.setCursor(new Cursor(Cursor.HAND_CURSOR));
        seePassword.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                seePasswordMouseClicked(evt);
            }
        });

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(userName, GroupLayout.PREFERRED_SIZE, 171, GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(password, GroupLayout.PREFERRED_SIZE, 171, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seePassword))
                            .addComponent(jLabel2)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(loginButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5))
                            .addComponent(registerButton))))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addComponent(userName, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(password, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                    .addComponent(seePassword))
                .addGap(38, 38, 38)
                .addComponent(loginButton, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerButton, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 159, GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(loginClose, GroupLayout.Alignment.TRAILING)
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(loginClose, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel3)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 156, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userNameActionPerformed(ActionEvent evt) {
    }

    private void loginCloseActionPerformed(ActionEvent evt) {//GEN-FIRST:event_loginCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_loginCloseActionPerformed

        private void registerButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        Register reg=new Register();
        reg.setVisible(true);
        reg.pack();
        reg.setLocationRelativeTo(null);
        reg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_registerButtonActionPerformed

    public void loginButtonActionPerformed(ActionEvent evt ){//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
       try {
           stmt = conn.createStatement();
            String logUser = userName.getText();
            String logPass = password.getText();
            String sql1 = "Select r.username,r.password,sum(vacantRoom)from register r, house where r.username='" + logUser + "'&& r.password = '" + logPass + "'";
            String sql = "Select Distinct(tenantId),outstandingAmount from tenant";
           Home hom =new Home();
           rs = stmt.executeQuery(sql1);
           if(rs.next()) {
               hom.setVisible(true);
               hom.pack();
               hom.setLocationRelativeTo(null);
               hom.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
               hom.vacantRooms.setText(Integer.toString(rs.getInt("sum(vacantRoom)")));
               check = true;
           }
           else JOptionPane.showMessageDialog(null, "password or username invalid");
           rs = stmt.executeQuery(sql);
           int sum =0;
           while(rs.next()){
               sum += rs.getInt("outstandingAmount");
           }
           hom.outstandingAmount.setText(Integer.toString(sum));
           this.dispose();
       }
            catch(HeadlessException|SQLException e){
                JOptionPane.showMessageDialog(null,e);
           }

       }

//GEN-LAST:event_loginButtonActionPerformed

    private void seePasswordMouseClicked(MouseEvent evt) {//GEN-FIRST:event_seePasswordMouseClicked
     password.setEchoChar((char)0);
// TODO add your handling code here:
    }//GEN-LAST:event_seePasswordMouseClicked

     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JButton loginButton;
    private JButton loginClose;
    private JPasswordField password;
    private JButton registerButton;
    private JLabel seePassword;
    private JTextField userName;
    // End of variables declaration//GEN-END:variables
}
